### PR TITLE
Make inventory step robust to empty queries 

### LINKED ISSUE #96: Empty queries are missing expected columns in WQP inventory
We currently define our grid cells using a set of lat/lon values in `_targets.R`, and expect that many users will do the same (although some will opt to use a shapefile as an alternative). However, we've noticed that if an AOI includes grid cells that come up empty when fetching the WQP inventory, we're missing columns that [we expected to be there](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/blob/main/1_inventory/src/get_wqp_inventory.R#L64-L67), namely `HorizontalCoordinateReferenceSystemDatumName`. So then, when building the inventory for that grid cell, `inventory_wqp` throws an error:

```r
* start branch p1_wqp_inventory_14fec229 
Inventorying WQP data for grid 12822, Temperature
x error branch p1_wqp_inventory_14fec229
Error: Can't subset columns that don't exist.
x Column `HorizontalCoordinateReferenceSystemDatumName` doesn't exist.
```

We should make this step more flexible to empty grid cells by accommodating situations where the CRS datum column (plz don't make me type it again... 😅) isn't returned.

### PR DESCRIPTION
**Pull request by lekoenig**
An empty query will not contain the column `HorizontalCoordinateReferenceSystemDatumName` and so this PR adds a `tryCatch` wrapper around the lines in `inventory_wqp()` that fetch the site metadata. If a query is _not_ empty, we use the site metadata to harmonize the site coordinate reference systems. But if the query is empty, this step is moot and we just want `inventory_wqp()` to quietly return an empty data frame without complaining about the missing datum column. 

Closes #96

### CODE REVIEW

File: 1_inventory/src/get_wqp_inventory.R [hunk 1]
```diff
@@ -60,12 +60,19 @@ inventory_wqp <- function(grid, char_names, wqp_args = NULL, max_tries = 3){
...
+  # Fetch missing CRS information from WQP. Note that an empty query will not
+  # contain CRS information. In the event that the lines below throw an error, 
+  # "Column `HorizontalCoordinateReferenceSystemDatumName` doesn't exist", return
+  # an empty data frame for the site location metadata. 
+  site_location_metadata <- tryCatch(
+    dataRetrieval::whatWQPsites(bBox = c(bbox$xmin, bbox$ymin, bbox$xmax, bbox$ymax)) %>%
+      select(MonitoringLocationIdentifier, HorizontalCoordinateReferenceSystemDatumName) %>%
+      filter(MonitoringLocationIdentifier %in% wqp_inventory$MonitoringLocationIdentifier),
+    error = function(e){
+      data.frame(MonitoringLocationIdentifier = character())
```
Comment (lindsayplatt) [inline 1_inventory/src/get_wqp_inventory.R:72]: Do we want to keep the datum column in the empty one? That way, the column still exists and future joining or row-binding won't fuss about it?
```suggestion
      data.frame(MonitoringLocationIdentifier = character(), HorizontalCoordinateReferenceSystemDatumName = character())
```

Comment (lindsayplatt) [reply 1_inventory/src/get_wqp_inventory.R:72]: Adding to this to say that this would only matter if _all_ of the branches within the single inventory pattern were empty (highly unlikely with how we have it set up). But if someone used this function and made their own separate targets rather than branching over everything, they may get some strange message if they try to combine on their own later (although, I am realizing that `tidyverse::bind_rows()` handles missing columns now compared to `rbind()`, so this might be moot.

**Review by lindsayplatt — APPROVED** [review]
I was able to recreate the error noted in #96 on the `main` branch. Switching to this branch and re-running the pipeline works and their is no error. 

The resulting `p1_wqp_inventory` object has the datum column if there were other grid cells that returned data and did not have the datum column present if it was the only grid cell. While I think that is fine and my testing shows that it shouldn't cause an issue, I've left one suggestion that you may consider to prevent unexpected failures.

File: 1_inventory/src/get_wqp_inventory.R (hunk 1 above)
Comment (lekoenig) [reply 1_inventory/src/get_wqp_inventory.R:72]: Yeah, I think I did leave the empty data frame minimal because of how `bind_rows()` handles missing columns, but I agree with your assessment and that we should explicitly add the datum column to avoid unexpected errors. Thanks for testing this out, @lindsayplatt!
